_target_: ray.tune.schedulers.PopulationBasedTraining
time_attr: cur_epoch
perturbation_interval: 70 # formerly, 50
# burn_in_period: 150
hyperparam_mutations:
  model:
    lr_init:
      _target_: ray.tune.loguniform
      lower: 1.0e-5
      upper: 5.0e-3
    dropout_rate:
      _target_: ray.tune.uniform
      lower: 0.0
      upper: 0.6
    cd_rate:
      _target_: ray.tune.uniform
      lower: 0.01
      upper: 0.7
    l2_gen_scale:
      _target_: ray.tune.loguniform
      lower: 1.0e-4
      upper: 1.0e-0
    l2_con_scale:
      _target_: ray.tune.loguniform
      lower: 1.0e-4
      upper: 1.0e-0
    kl_co_scale:
      _target_: ray.tune.loguniform
      lower: 1.0e-6
      upper: 1.0e-4
    kl_ic_scale:
      _target_: ray.tune.loguniform
      lower: 1.0e-5
      upper: 1.0e-3
quantile_fraction: 0.25
resample_probability: 0.25
custom_explore_fn: null
log_config: True
require_attrs: True
synch: True
