defaults:
  - model: nlb_area2_bump
  - datamodule: nlb_area2_bump
  - callbacks: nlb
  - logger: default
  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog
  - _self_

seed: 0

trainer:
  _target_: pytorch_lightning.Trainer
  gradient_clip_val: 200
  max_epochs: 1_000
  log_every_n_steps: 5
  # Prevent console output by individual models
  enable_progress_bar: False
  enable_model_summary: False

# Allow PBT to handle LR scheduling
model.lr_decay: 1.0

callbacks:
  model_checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    dirpath: "."
    filename: last
  tune_report_checkpoint_callback:
    _target_: ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback
    metrics:
      - valid/recon_smth
      - cur_epoch
    filename: tune.ckpt
    "on": validation_end
  learning_rate_monitor:
    _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: epoch

posterior_sampling:
  best_ckpt: false
  fn:
    _target_: lfads_torch.post_run.analysis.run_posterior_sampling
    filename: lfads_output.h5
    num_samples: 50

logger:
  tensorboard_logger:
    _target_: pytorch_lightning.loggers.TensorBoardLogger
    # Configure logger so PTL and ray use the same TB file.
    save_dir:
      _target_: ray.tune.get_trial_dir
    version: "."
    name: ""
