_target_: lfads_torch.datamodules.BasicDataModule
datafile_pattern: ${relpath:datasets/dmfc_rsg-05ms-val.h5}
batch_keys:
  - behavior
attr_keys:
  - psth
  - train_cond_idx
  - valid_cond_idx
  - train_jitter
  - valid_jitter
batch_size: 256
