_target_: lfads_torch.datamodules.nlb.LFADSNLBDataModule
dataset_name: dmfc_rsg
phase: val
bin_width: 5
batch_size: 300
reshuffle_tv_seed: 42
num_workers: 0
sv_rate: 0.0
sv_seed: 0
# Name with `dm_` to avoid overlap w/ model HPS (per `pytorch_lightning==1.4.9`)
dm_ic_enc_seq_len: ${model.ic_enc_seq_len}
